#conda env create -f environment.yml
#conda activate law_qa_env
#conda env update -f environment.yml --prune

name: law_qa_env
channels:
  - defaults
dependencies:
  - python=3.10.13
  - pip=23.3
  - pip:
      - fastapi==0.104.1
      - uvicorn==0.24.0.post1
      - langchain==0.0.335
      - openai==1.2.3
      - beautifulsoup4==4.12.2
      - PyPDF2==3.0.1
      - tiktoken
      - qdrant-client==1.7.0
      - pypdf
      - flashrank
      - transformers
      - transformers[sentencepiece]
      - sacremoses
      - torch
      - langchain-community
      - doctran

